openapi: "3.0.0"
info:
  version: 2.0.0
  title: FHIR-247
  description: An FHIR API example that uses a methodology to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Developer
    email: danang.kastowo@labs247.id
    # url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://fhir.labs247.id/v2
paths:
  /administrative-gender:
    get:
      tags:
        - Reference
      description: |
        The gender of a person used for administrative purposes.
      operationId: reference.getAdministrativeGenders
      responses:
        '200':
          description: administrative-gender
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdministrativeGender'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
    post:
      tags:
        - Reference
      description: |
        The gender of a person used for administrative purposes.
      operationId: reference.addAdministrativeGender
      requestBody:
        description: Create a new administrative gender
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdministrativeGender'

      responses:
        '200':
          description: administrative-gender
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
  /administrative-gender/{code}:
    get:
      tags:
        - Reference
      description: |
        The gender of a person used for administrative purposes.
      operationId: reference.getAdministrativeGender
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: administrative-gender
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdministrativeGender'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
    put:
      tags:
        - Reference
      description: |
        The gender of a person used for administrative purposes.
      operationId: reference.updateAdministrativeGender
      requestBody:
        description: Update a administrative gender
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdministrativeGender'
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: administrative-gender
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
    delete:
      tags:
        - Reference
      description: |
        The gender of a person used for administrative purposes.
      operationId: reference.deleteAdministrativeGender
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: administrative-gender
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
components:
  schemas:
    AdministrativeGender:
      type: object
      properties:
        code:
          type: string
        display:
          type: string
        definition:
          type: string
    DefaultMessage:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string