openapi: "3.0.0"
info:
  version: 2.0.0
  title: FHIR-247
  description: An FHIR API example that uses a methodology to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Developer
    email: danang.kastowo@labs247.id
    # url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://fhir.labs247.id/v2
paths:
  /marital-status:
    get:
      tags:
        - Reference
      description: |
        This value set defines the set of codes that can be used to indicate the marital status of a person.
      operationId: reference.getMaritalStatuses
      responses:
        '200':
          description: marital-status
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MaritalStatus'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
    post:
      tags:
        - Reference
      description: |
        This value set defines the set of codes that can be used to indicate the marital status of a person.
      operationId: reference.addMaritalStatus
      requestBody:
        description: Create a new marital status
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaritalStatus'
      responses:
        '200':
          description: marital-status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
  /marital-status/{code}:
    get:
      tags:
        - Reference
      description: |
        This value set defines the set of codes that can be used to indicate the marital status of a person.
      operationId: reference.getMaritalStatus
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: marital-status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaritalStatus'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
    put:
      tags:
        - Reference
      description: |
        This value set defines the set of codes that can be used to indicate the marital status of a person.
      operationId: reference.updateMaritalStatus
      requestBody:
        description: Update a marital status
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaritalStatus'
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: marital-status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
    delete:
      tags:
        - Reference
      description: |
        This value set defines the set of codes that can be used to indicate the marital status of a person.
      operationId: reference.deleteMaritalStatus
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: marital-status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultMessage'
components:
  schemas:
    MaritalStatus:
      type: object
      properties:
        code:
          type: string
        system:
          type: string
          format: uri
        display:
          type: string
        definition:
          type: string
    DefaultMessage:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string